interface envVariables {
  PIPEDREAM_API_KEY: string;
  GOOGLE_SHEETS_SERVICE_ACCOUNT: string; 
  GOOGLE_SHEETS_PRIVATE_KEY: string; 
  GOOGLE_SHEETS_SUBSCRIBERS_ID: string; 
  GOOGLE_SHEETS_SUBSCRIBERS_PAGE: string;
}

export const envVariables: envVariables = {
    PIPEDREAM_API_KEY: process.env.PIPEDREAM_API_KEY!,
    GOOGLE_SHEETS_SERVICE_ACCOUNT: process.env.GOOGLE_SHEETS_SERVICE_ACCOUNT!,
    GOOGLE_SHEETS_PRIVATE_KEY: process.env.GOOGLE_SHEETS_PRIVATE_KEY!,
    GOOGLE_SHEETS_SUBSCRIBERS_ID: process.env.GOOGLE_SHEETS_SUBSCRIBERS_ID!,
    GOOGLE_SHEETS_SUBSCRIBERS_PAGE: process.env.GOOGLE_SHEETS_SUBSCRIBERS_PAGE!,
}